apiVersion: v1
kind: Service
metadata:
    name: "kubernete-5312"
    labels:
        app: "kubernete-5312"
spec:
    type: LoadBalancer
    ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
    selector:
        app: "kubernete-5312"