on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - uses: azure/docker-login@v1
      with:
        login-server: containerregistryproject2.azurecr.io
        username: ${{ secrets.acr_containerregistryproject2_username }}
        password: ${{ secrets.acr_containerregistryproject2_password }}
    
    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/neighborlyfrontend" -f  "Dockerfile" -t containerregistryproject2.azurecr.io/kubernete:${{ github.sha }} --label dockerfile-path=Dockerfile
        docker push containerregistryproject2.azurecr.io/kubernete:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      with:
         kubeconfig: ${{ secrets.aks_kubernete_kubeConfig }}
      id: login
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep kubernete91e9 | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace kubernete91e9`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: kubernete91e9
        container-registry-url: containerregistryproject2.azurecr.io
        container-registry-username: ${{ secrets.acr_containerregistryproject2_username }}
        container-registry-password: ${{ secrets.acr_containerregistryproject2_password }}
        secret-name: kubernetedockerauth
       
    - uses: azure/k8s-deploy@v1.2
      with:
        namespace: kubernete91e9
        manifests: |
          manifests/deployment.yml
          manifests/service.yml
        images: |
          containerregistryproject2.azurecr.io/kubernete:${{ github.sha }}
        imagepullsecrets: |
          kubernetedockerauth
